In [10]:
from torch_geometric.datasets import Planetoid
import torch
import torch.nn.functional as F
from torch_geometric.utils import add_self_loops, degree
import networkx as nx
import numpy as np
import matplotlib.pyplot as plt
import pickle
import json
from pathlib import Path
import networkx as nx
from torch_geometric.data import InMemoryDataset, download_url
from torch_geometric.data import Data
import os.path as osp
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import torch_geometric.transforms as T
import pandas as pd
from torch_geometric.utils import from_networkx, to_networkx
from copy import deepcopy
import pickle
import torch.nn as nn
from torch_geometric.nn import GCNConv
from sklearn.manifold import TSNE
from ge import DeepWalk


ModuleNotFoundError: No module named 'ge'

In [3]:
G = nx.karate_club_graph()

labels = np.asarray([G.nodes[i]['club'] != 'Mr. Hi' for i in G.nodes]).astype(np.int64)


In [9]:
m = TSNE(learning_rate=20, random_state=42)
tsne_features = m.fit_transform(list(embeddings.values()))

In [ ]:
# train the model and generate embeddings
model = DeepWalk(H, walk_length=10, num_walks=80, workers=1)
model.train(window_size=5,iter=3)

embeddings = model.get_embeddings()

In [1]:
class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = GCNConv(data.num_features, 16)
        self.conv2 = GCNConv(16, int(data.num_classes))

    def forward(self):
        x, edge_index = data.x, data.edge_index
        x = F.relu(self.conv1(x, edge_index))
        # x = F.dropout(x, training=self.training)
        x = self.conv2(x, edge_index)
        return F.log_softmax(x, dim=1)

NameError: name 'torch' is not defined

In [3]:
def plot_dataset(dataset):
    edges_raw = dataset.data.edge_index.numpy()
    edges = [(x, y) for x, y in zip(edges_raw[0, :], edges_raw[1, :])]
    labels = dataset.data.y.numpy()

    G = nx.Graph()
    G.add_nodes_from(list(range(np.max(edges_raw))))
    G.add_edges_from(edges)
    plt.subplot(111)
    options = {
                'node_size': 30,
                'width': 0.2,
    }
    nx.draw(G, with_labels=False, node_color=labels.tolist(), cmap=plt.cm.tab10, font_weight='bold', **options)
    plt.show()

In [7]:
scale = StandardScaler()
# Opening JSON file
f = open('/gstore/scratch/u/hysii/nlp/original_dataset')
  
# returns JSON object as 
# a dictionary
json_data = json.load(f)


In [8]:
all_sympts = []

for key, other_info in json_data.items():
    for s in other_info['symptoms'].keys():
        all_sympts.append(s)


In [9]:
unique_sympts = []
for i, sympt in enumerate(all_sympts):
    counter = 0
    
    for idx, s in enumerate(all_sympts):
        if sympt == s and i != idx:
            counter += 1
    
    if counter == 0:
        unique_sympts.append(sympt)

In [10]:
path_to_symptoms = {}

for key, other_info in json_data.items():
    symp_lst = []
    for s in unique_sympts:
        if s in other_info['symptoms'].keys():
            print(s)
            symp_lst.append(s)
    
    if len(symp_lst) != 0:
        path_to_symptoms[key] = symp_lst

larmes
vo_violent
ww_bouger
pyrosis
ww_bouffe
pale
rectorragie
ménorr
ballon_abdo
ww_valsalva
obstipation
dysarthrie
diplopie
fatigabilité_msk
claud_mâchoire
posttus_emesis
insp_siffla
contact_allergie
bw_bending
faiblesse faciale
footnumb
paralysie_visage
toux_Aboy
pls_irreg
prurit_occ
prurit_nasal
rds_anorexie
flushing
dysp_effort
laryngospasme
spasmes_msk
trismus
spasme_trapeze
protu_langue
regard_dévié
gain_poids
ulcères_bouche
angor_accelere
rds_sg
confusion
etouff
psy_depers
impression_mort
boire_ped
apnee
erytheme_occ
convulsion
pertes_vag
selles_pale


In [11]:
with open('/gstore/scratch/u/hysii/nlp/unique_symptoms.json', 'w') as f:
    json.dump(path_to_symptoms, f)

In [12]:
with open('/gstore/scratch/u/hysii/nlp/unique_symptoms.json', 'r') as f:
    data = json.load(f)

In [13]:
G = nx.Graph(data)

with open('/gstore/scratch/u/hysii/nlp/graph.pckl', 'wb') as f:
    graph = pickle.dump(G, f)

embeddings = np.array(list(dict(G.degree()).values()))
scale = StandardScaler()
embeddings = scale.fit_transform(embeddings.reshape(-1,1))

In [17]:
labels = []

for idx, (key, u_sympts) in enumerate(path_to_symptoms.items()):
    labels.append(idx)
    for s in u_sympts:
        labels.append(idx)

labels = np.array(labels)

In [30]:
embeddings

array([[-0.36848377],
       [-0.36848377],
       [-0.36848377],
       [ 0.83309374],
       [ 2.03467124],
       [ 2.03467124],
       [ 3.23624875],
       [ 0.83309374],
       [-0.36848377],
       [-0.36848377],
       [ 2.03467124],
       [-0.36848377],
       [-0.36848377],
       [ 0.83309374],
       [-0.36848377],
       [-0.36848377],
       [-0.36848377],
       [ 5.63940376],
       [-0.36848377],
       [-0.36848377],
       [-0.36848377],
       [ 0.83309374],
       [ 2.03467124],
       [ 0.83309374],
       [ 2.03467124],
       [-0.36848377],
       [-0.36848377],
       [-0.36848377],
       [-0.36848377],
       [-0.36848377],
       [-0.36848377],
       [-0.36848377],
       [-0.36848377],
       [-0.36848377],
       [-0.36848377],
       [-0.36848377],
       [-0.36848377],
       [-0.36848377],
       [-0.36848377],
       [-0.36848377],
       [-0.36848377],
       [-0.36848377],
       [-0.36848377],
       [-0.36848377],
       [-0.36848377],
       [-0

In [26]:
class MyDataset(InMemoryDataset):
    def __init__(self, root, transform=None, pre_transform=None):
        super(MyDataset, self).__init__(root, transform, None, None)
        data = from_networkx(G)

        data.num_nodes = G.number_of_nodes()
        
        # embedding 
        data.x = torch.from_numpy(embeddings).type(torch.float32)
        
        # labels
        y = torch.from_numpy(labels).type(torch.long)
        data.y = y.clone().detach()
        
        data.num_classes = len(path_to_symptoms.keys())

        # splitting the data into train, validation and test
        X_train, X_test, y_train, y_test = train_test_split(pd.Series(list(G.nodes)), 
                                                            pd.Series(labels),
                                                            test_size=0.30, 
                                                            random_state=42)
        
        n_nodes = G.number_of_nodes()
        # create train and test masks for data
        train_mask = torch.zeros(n_nodes, dtype=torch.bool)
        test_mask = torch.zeros(n_nodes, dtype=torch.bool)
        train_mask[X_train.index] = True
        test_mask[X_test.index] = True
        data['train_mask'] = train_mask
        data['test_mask'] = test_mask

        self.data, self.slices = self.collate([data])
        
    def _download(self):
        return

    def _process(self):
        return

    def __repr__(self):
        return '{}()'.format(self.__class__.__name__)

In [32]:
dataset = MyDataset(Path('/gstore/scratch/u/hysii/nlp/graph.pckl'))
data = dataset[0]
print(dataset[0])

Data(edge_index=[2, 98], num_nodes=75, x=[75, 1], y=[75], num_classes=26, train_mask=[75], test_mask=[75])


In [28]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
data =  data.to(device)
model = Net().to(device) 

In [29]:
torch.manual_seed(42)

optimizer_name = "Adam"
lr = 1e-1
optimizer = getattr(torch.optim, optimizer_name)(model.parameters(), lr=lr)
epochs = 200

def train():
  model.train()
  optimizer.zero_grad()
  F.nll_loss(model()[data.train_mask], data.y[data.train_mask]).backward()
  optimizer.step()

@torch.no_grad()
def test():
  model.eval()
  logits = model()
  mask1 = data['train_mask']
  pred1 = logits[mask1].max(1)[1]
  acc1 = pred1.eq(data.y[mask1]).sum().item() / mask1.sum().item()
  mask = data['test_mask']
  pred = logits[mask].max(1)[1]
  acc = pred.eq(data.y[mask]).sum().item() / mask.sum().item()
  return acc1,acc

for epoch in range(1, epochs):
  train()

train_acc,test_acc = test()

print('#' * 70)
print('Train Accuracy: %s' %train_acc )
print('Test Accuracy: %s' % test_acc)
print('#' * 70)

######################################################################
Train Accuracy: 0.25
Test Accuracy: 0.08695652173913043
######################################################################


In [44]:
mask1 = data['train_mask']
print(mask1)
logits = model()
pred1 = logits[mask1].max(1)[1]
print(pred1)
acc1 = pred1.eq(data.y[mask1]).sum().item() / mask1.sum().item()
print(pred1.eq(data.y[mask1]).sum().item())
print9
mask = data['test_mask']
pred = logits[mask].max(1)[1]
acc = pred.eq(data.y[mask]).sum().item() / mask.sum().item()

tensor([False,  True,  True,  True, False, False,  True,  True,  True, False,
        False,  True, False,  True,  True,  True, False,  True, False,  True,
         True,  True, False,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True, False, False, False,  True,  True,  True, False,
        False,  True, False,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True, False,  True,  True,  True,
         True, False,  True, False, False,  True, False,  True,  True, False,
         True,  True,  True,  True,  True])
tensor([ 8,  8, 17,  3, 17,  8,  8, 17,  8,  8,  6,  8,  8, 17, 17,  7,  8,  8,
         8, 17, 17, 10, 10, 10, 13, 13, 17,  8,  8, 10, 10, 10,  8, 17, 17,  8,
         8,  8, 21, 21, 21, 21, 21,  8, 17, 10, 10, 17, 10, 10, 10,  8])
13


In [ ]:
labels

: 

In [ ]:
G.process_node_features()